const carName = 'Jeep';
let maxCarSpeed = '180';
let carOwner = 'Diomid';
alert(carName);
alert(maxCarSpeed);
alert(carOwner);
maxCarSpeed = '170';
carOwner = 'Olga';
console.log('Скорость авто изменилась на', maxCarSpeed);
console.log('Сменился владелец', carOwner);
maxCarSpeed = '160';
carOwner = 'Gleb';
console.log('Скорость авто изменилась на', maxCarSpeed);
console.log('Сменился владелец', carOwner);
maxCarSpeed = '150';
carOwner = 'Evgenia';
console.log('Скорость авто изменилась на', maxCarSpeed);
console.log('Сменился владелец', carOwner);