const header = 'Всем привет! Меня зовут';
const myName = 'Diomid.';
const text1 = 'Сейчас я изучаю язык программирования';
const programmingLanguage = 'JavaScript';
const text2 = 'на курсе по';
const text3 = 'у';
const courseCreatorName = 'Владилена Минина.';
const text4 = 'Я хочу стать веб-разработчиком, потому что';
const reasonText = 'мне это нравится.';
const text5 = 'До этого я изучал';
const numberOfMonth = '1 месяц.';
const text6 = 'Я уверен, что пройду данный курс до конца!';
const allInfo = `${header} ${myName} ${text1} ${programmingLanguage} ${text2} ${programmingLanguage} ${text3} ${courseCreatorName} ${text4} ${reasonText} ${text5} ${programmingLanguage} ${numberOfMonth} ${text6}`;
console.log(allInfo);